// src/components/Onboarding.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { useI18n } from "vue-i18n";
import { testConnection } from "@/services/apiClient";
import type { ConnectionTestResult } from "@/services/apiClientTypes";
import {
  DEFAULT_BASE_URL,
  ENDPOINT_TYPE_LABEL,
  PRESET_MODELS,
  type EndpointType,
} from "@/services/presets";
import { useConfigStore } from "@/stores/config";

const props = defineProps<{ open: boolean }>();
const emit = defineEmits<{ complete: [] }>();

const { t } = useI18n();
const toast = useToast();
const cfg = useConfigStore();

const isOpen = ref(props.open);
watch(() => props.open, (v) => (isOpen.value = v));
watch(isOpen, (v) => {
  // When user dismisses via Escape (we don't allow outside-click), bail out.
  if (!v && props.open) emit("complete");
});

const step = ref<1 | 2>(1);

// Step 1 state
const epType = ref<EndpointType>("openai");
const epName = ref("OpenAI");
const epBaseUrl = ref(DEFAULT_BASE_URL.openai);
const epApiKey = ref("");
const urlDirty = ref(false);
const nameDirty = ref(false);
const testing = ref(false);
const testResult = ref<ConnectionTestResult | null>(null);
const endpointId = ref<string>("");

// Step 2 state
const modelMode = ref<"preset" | "custom">("preset");
const presetIdx = ref(0);
const customModelId = ref("");
const modelLabel = ref("");
const labelDirty = ref(false);
const finishing = ref(false);

// Auto-fill name + URL when type switches (unless user edited)
watch(epType, () => {
  if (!urlDirty.value) epBaseUrl.value = DEFAULT_BASE_URL[epType.value];
  if (!nameDirty.value) epName.value = ENDPOINT_TYPE_LABEL[epType.value];
  testResult.value = null;
  presetIdx.value = 0;
});

const presets = computed(() => PRESET_MODELS[epType.value]);

// Sync the model label with the chosen preset / custom name unless user
// typed their own label.
watch([modelMode, presetIdx, customModelId], () => {
  if (labelDirty.value) return;
  if (modelMode.value === "preset" && presets.value[presetIdx.value]) {
    modelLabel.value = presets.value[presetIdx.value].label;
  } else if (modelMode.value === "custom") {
    modelLabel.value = customModelId.value || "";
  }
});

const presetOptions = computed(() =>
  presets.value.map((p, i) => ({
    label: p.label,
    value: String(i),
    description: p.model_id,
  }))
);

const presetIdxStr = computed({
  get: () => String(presetIdx.value),
  set: (v: string) => (presetIdx.value = Number(v)),
});

const transientEndpoint = computed(() => ({
  id: "draft",
  name: epName.value.trim() || ENDPOINT_TYPE_LABEL[epType.value],
  type: epType.value,
  base_url: epBaseUrl.value.trim(),
  api_key: epApiKey.value.trim(),
}));

async function handleTest() {
  if (!epBaseUrl.value.trim() || !epApiKey.value.trim()) {
    toast.add({ title: t("onboarding.needsBoth"), color: "warning" });
    return;
  }
  testing.value = true;
  testResult.value = null;
  testResult.value = await testConnection(transientEndpoint.value);
  testing.value = false;
}

async function handleNext() {
  if (!epApiKey.value.trim()) {
    toast.add({ title: t("onboarding.needsBoth"), color: "warning" });
    return;
  }
  if (endpointId.value) {
    await cfg.updateEndpoint(endpointId.value, {
      name: transientEndpoint.value.name,
      type: transientEndpoint.value.type,
      base_url: transientEndpoint.value.base_url,
      api_key: transientEndpoint.value.api_key,
    });
  } else {
    endpointId.value = await cfg.addEndpoint({
      name: transientEndpoint.value.name,
      type: transientEndpoint.value.type,
      base_url: transientEndpoint.value.base_url,
      api_key: transientEndpoint.value.api_key,
    });
  }
  step.value = 2;
}

function handleBack() {
  step.value = 1;
}

async function handleSkip() {
  if (endpointId.value) {
    await cfg.removeEndpoint(endpointId.value);
    endpointId.value = "";
  }
  await cfg.update({ onboarding_completed: true });
  emit("complete");
}

async function handleFinish() {
  const modelId =
    modelMode.value === "preset"
      ? presets.value[presetIdx.value]?.model_id
      : customModelId.value.trim();
  if (!modelId) {
    toast.add({ title: t("onboarding.modelRequired"), color: "warning" });
    return;
  }
  if (!endpointId.value) {
    toast.add({ title: t("onboarding.endpointMissing"), color: "error" });
    step.value = 1;
    return;
  }
  finishing.value = true;
  await cfg.addModel({
    endpoint_id: endpointId.value,
    model_id: modelId,
    label: modelLabel.value.trim() || modelId,
    is_custom: modelMode.value === "custom",
  });
  await cfg.update({ onboarding_completed: true });
  finishing.value = false;
  emit("complete");
}
</script>

<template>
  <UModal
    v-model:open="isOpen"
    :dismissible="false"
    :close="false"
    :ui="{ content: 'max-w-[600px]' }"
  >
    <template #content>
      <div class="p-6 md:p-8 flex flex-col gap-4">
        <!-- Masthead -->
        <div class="flex items-center justify-between gap-3">
          <span class="text-[10.5px] font-mono uppercase tracking-[0.16em] text-toned">
            {{ t("onboarding.eyebrow") }}
          </span>
          <span class="text-[10.5px] font-mono tracking-wider text-toned">
            {{ t("onboarding.stepLabel", { current: step, total: 2 }) }}
          </span>
        </div>

        <h2 class="font-semibold leading-tight tracking-tight">
          <span class="block text-3xl text-highlighted">
            {{ step === 1 ? t("onboarding.step1Title") : t("onboarding.step2Title") }}
          </span>
          <span class="block text-xl text-muted italic">
            {{ step === 1 ? t("onboarding.step1Subtitle") : t("onboarding.step2Subtitle") }}
          </span>
        </h2>
        <p class="text-sm text-muted leading-relaxed">
          {{ step === 1 ? t("onboarding.step1Body") : t("onboarding.step2Body") }}
        </p>

        <!-- Step 1: endpoint form -->
        <div v-if="step === 1" class="flex flex-col gap-4">
          <div class="grid grid-cols-1 md:grid-cols-[1.2fr_1fr] gap-3">
            <UFormField :label="t('endpoint.name')">
              <UInput
                v-model="epName"
                placeholder="OpenAI"
                autofocus
                class="w-full"
                @update:model-value="nameDirty = true"
              />
            </UFormField>
            <UFormField :label="t('endpoint.type')">
              <USelect
                v-model="epType"
                :items="[
                  { label: t('endpoint.typeOpenai'), value: 'openai' },
                  { label: t('endpoint.typeGoogle'), value: 'google' },
                ]"
                class="w-full"
              />
            </UFormField>
          </div>

          <UFormField :label="t('endpoint.url')" :description="t('endpoint.urlHint')">
            <UInput
              v-model="epBaseUrl"
              :placeholder="DEFAULT_BASE_URL[epType]"
              class="w-full font-mono"
              @update:model-value="urlDirty = true; testResult = null"
            />
          </UFormField>

          <UFormField :label="t('endpoint.apiKey')" :description="t('endpoint.apiKeyHint')">
            <UInput
              v-model="epApiKey"
              type="password"
              :placeholder="epType === 'openai' ? 'sk-...' : 'AIza...'"
              class="w-full font-mono"
              @update:model-value="testResult = null"
            />
          </UFormField>

          <div class="flex items-center gap-3">
            <UButton
              variant="outline"
              icon="i-lucide-plug"
              :loading="testing"
              :disabled="!epBaseUrl.trim() || !epApiKey.trim()"
              @click="handleTest"
            >
              {{ testing ? t("settings.testing") : t("onboarding.test") }}
            </UButton>
            <span
              v-if="testResult && !testing"
              :class="[
                'inline-flex items-center gap-1 text-sm',
                testResult.ok ? 'text-success' : 'text-error',
              ]"
            >
              <UIcon
                :name="testResult.ok ? 'i-lucide-circle-check' : 'i-lucide-circle-alert'"
                class="size-3.5"
              />
              {{
                testResult.ok
                  ? testResult.modelCount !== undefined
                    ? t("settings.testModels", { count: testResult.modelCount })
                    : t("settings.testOk")
                  : testResult.message
              }}
            </span>
          </div>
        </div>

        <!-- Step 2: model form -->
        <div v-if="step === 2" class="flex flex-col gap-4">
          <div class="flex items-center gap-2 text-sm text-muted">
            <span class="text-[10.5px] font-mono uppercase tracking-wider text-toned">
              {{ t("model.endpoint") }}
            </span>
            <UBadge color="neutral" variant="subtle" size="sm">
              {{ epName }} · {{ ENDPOINT_TYPE_LABEL[epType] }}
            </UBadge>
          </div>

          <UFormField :label="t('model.modelId')">
            <USelect
              v-if="modelMode === 'preset'"
              v-model="presetIdxStr"
              :items="presetOptions"
              class="w-full"
            />
            <UInput
              v-else
              v-model="customModelId"
              :placeholder="t('model.customPlaceholder')"
              class="w-full font-mono"
            />
          </UFormField>

          <UFormField :label="t('model.customToggle')" :description="t('model.customHint')">
            <div class="flex items-center gap-3 h-9">
              <USwitch
                v-model="modelMode"
                :true-value="'custom'"
                :false-value="'preset'"
              />
              <span class="text-sm text-muted">
                {{ modelMode === "custom" ? t("model.customOn") : t("model.customOff") }}
              </span>
            </div>
          </UFormField>

          <UFormField :label="t('model.label')" :description="t('model.labelHint')">
            <UInput
              v-model="modelLabel"
              :placeholder="t('model.labelPlaceholder')"
              class="w-full"
              @update:model-value="labelDirty = true"
            />
          </UFormField>
        </div>

        <!-- Actions -->
        <USeparator class="mt-2" />
        <div class="flex items-center justify-between gap-3">
          <UButton
            v-if="step === 1"
            variant="ghost"
            color="neutral"
            @click="handleSkip"
          >
            {{ t("onboarding.skip") }}
          </UButton>
          <UButton
            v-else
            variant="ghost"
            color="neutral"
            icon="i-lucide-arrow-left"
            @click="handleBack"
          >
            {{ t("onboarding.back") }}
          </UButton>

          <UButton
            v-if="step === 1"
            color="primary"
            trailing-icon="i-lucide-arrow-right"
            :disabled="testing || !epApiKey.trim()"
            @click="handleNext"
          >
            {{ t("onboarding.next") }}
          </UButton>
          <UButton
            v-else
            color="primary"
            trailing-icon="i-lucide-arrow-right"
            :loading="finishing"
            @click="handleFinish"
          >
            {{ t("onboarding.finish") }}
          </UButton>
        </div>
      </div>
    </template>
  </UModal>
</template>

// src_legacy/components/Onboarding.tsx
import { useEffect, useMemo, useState } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { useTranslation } from "react-i18next";
import { Plug, CheckCircle2, AlertCircle, ArrowRight, ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Field, Label } from "@/components/ui/Label";
import { Input } from "@/components/ui/Input";
import { Switch } from "@/components/ui/Switch";
import { Select, SelectItem } from "@/components/ui/Select";
import { Hint } from "@/components/ui/Hint";
import { testConnection } from "@/services/apiClient";
import type { ConnectionTestResult } from "@/services/apiClientTypes";
import { useConfig } from "@/services/store";
import { useToast } from "@/components/ui/Toast";
import {
  DEFAULT_BASE_URL,
  ENDPOINT_TYPE_LABEL,
  PRESET_MODELS,
  type EndpointType,
} from "@/services/presets";
import { cn } from "@/lib/utils";

interface Props {
  open: boolean;
  /** Fires when the user dismisses (skip / finish / esc). */
  onComplete: () => void;
}

type Step = 1 | 2;

/**
 * Two-step first-launch wizard.
 *
 *   Step 1 — Add an endpoint (name, type, base_url, api_key)
 *   Step 2 — Add a model pinned to that endpoint
 *
 * On Finish we persist `onboarding_completed: true`; the endpoint and
 * model writes happen incrementally as the user proceeds.
 */
export function OnboardingDialog({ open, onComplete }: Props) {
  const { t } = useTranslation();
  const { push } = useToast();
  const update = useConfig((s) => s.update);
  const addEndpoint = useConfig((s) => s.addEndpoint);
  const addModel = useConfig((s) => s.addModel);
  const removeEndpoint = useConfig((s) => s.removeEndpoint);

  const [step, setStep] = useState<Step>(1);

  // ── Step 1 state ──────────────────────────────────────────────
  const [epType, setEpType] = useState<EndpointType>("openai");
  const [epName, setEpName] = useState("OpenAI");
  const [epBaseUrl, setEpBaseUrl] = useState(DEFAULT_BASE_URL.openai);
  const [epApiKey, setEpApiKey] = useState("");
  // Tracks the URL the user has explicitly edited so we don't stomp it
  // when they switch type back and forth.
  const [urlDirty, setUrlDirty] = useState(false);
  const [nameDirty, setNameDirty] = useState(false);
  const [testing, setTesting] = useState(false);
  const [testResult, setTestResult] = useState<ConnectionTestResult | null>(null);
  // Persisted across step transitions — when the user goes Back, we want
  // the same endpoint they just created, not a fresh one.
  const [endpointId, setEndpointId] = useState<string>("");

  // ── Step 2 state ──────────────────────────────────────────────
  const [modelMode, setModelMode] = useState<"preset" | "custom">("preset");
  const [presetIdx, setPresetIdx] = useState(0);
  const [customModelId, setCustomModelId] = useState("");
  const [modelLabel, setModelLabel] = useState("");
  const [labelDirty, setLabelDirty] = useState(false);
  const [finishing, setFinishing] = useState(false);

  // Reset the type-driven defaults whenever the user switches provider,
  // unless they've explicitly typed something in those fields.
  useEffect(() => {
    if (!urlDirty) setEpBaseUrl(DEFAULT_BASE_URL[epType]);
    if (!nameDirty) setEpName(ENDPOINT_TYPE_LABEL[epType]);
    setTestResult(null);
  }, [epType, urlDirty, nameDirty]);

  // Keep step-2 label in sync with selected preset / custom model name.
  const presets = PRESET_MODELS[epType];
  useEffect(() => {
    if (labelDirty) return;
    if (modelMode === "preset" && presets[presetIdx]) {
      setModelLabel(presets[presetIdx].label);
    } else if (modelMode === "custom") {
      setModelLabel(customModelId || "");
    }
  }, [modelMode, presetIdx, customModelId, labelDirty, presets]);

  // Snap presetIdx back to 0 when the type changes so we don't index past
  // the new (shorter) preset list.
  useEffect(() => {
    setPresetIdx(0);
  }, [epType]);

  const transientEndpoint = useMemo(
    () => ({
      id: "draft",
      name: epName.trim() || ENDPOINT_TYPE_LABEL[epType],
      type: epType,
      base_url: epBaseUrl.trim(),
      api_key: epApiKey.trim(),
    }),
    [epName, epType, epBaseUrl, epApiKey]
  );

  const handleTest = async () => {
    if (!epBaseUrl.trim() || !epApiKey.trim()) {
      push({ title: t("onboarding.needsBoth"), intent: "warn" });
      return;
    }
    setTesting(true);
    setTestResult(null);
    const r = await testConnection(transientEndpoint);
    setTestResult(r);
    setTesting(false);
  };

  const handleNext = async () => {
    if (!epApiKey.trim()) {
      push({ title: t("onboarding.needsBoth"), intent: "warn" });
      return;
    }
    // If user retraces back-then-forward, edit the existing endpoint
    // in place rather than creating duplicates.
    if (endpointId) {
      await useConfig.getState().updateEndpoint(endpointId, {
        name: transientEndpoint.name,
        type: transientEndpoint.type,
        base_url: transientEndpoint.base_url,
        api_key: transientEndpoint.api_key,
      });
    } else {
      const id = await addEndpoint({
        name: transientEndpoint.name,
        type: transientEndpoint.type,
        base_url: transientEndpoint.base_url,
        api_key: transientEndpoint.api_key,
      });
      setEndpointId(id);
    }
    setStep(2);
  };

  const handleBack = () => {
    setStep(1);
  };

  const handleSkip = async () => {
    // If they Started step 2 but didn't finish, clean up the half-saved
    // endpoint so we don't leave a configured-but-no-model state behind.
    if (endpointId) {
      await removeEndpoint(endpointId);
      setEndpointId("");
    }
    await update({ onboarding_completed: true });
    onComplete();
  };

  const handleFinish = async () => {
    const modelId =
      modelMode === "preset" ? presets[presetIdx]?.model_id : customModelId.trim();
    if (!modelId) {
      push({ title: t("onboarding.modelRequired"), intent: "warn" });
      return;
    }
    if (!endpointId) {
      push({ title: t("onboarding.endpointMissing"), intent: "error" });
      setStep(1);
      return;
    }
    setFinishing(true);
    await addModel({
      endpoint_id: endpointId,
      model_id: modelId,
      label: modelLabel.trim() || modelId,
      is_custom: modelMode === "custom",
    });
    await update({ onboarding_completed: true });
    setFinishing(false);
    onComplete();
  };

  return (
    <Dialog.Root open={open}>
      <Dialog.Portal>
        <Dialog.Overlay
          className={cn(
            "fixed inset-0 z-[150] bg-ink/55 backdrop-blur-sm",
            "data-[state=open]:animate-in data-[state=open]:fade-in-0 duration-300"
          )}
        />
        <Dialog.Content
          onEscapeKeyDown={(e) => e.preventDefault()}
          onPointerDownOutside={(e) => e.preventDefault()}
          onInteractOutside={(e) => e.preventDefault()}
          className={cn(
            "fixed left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 z-[151]",
            "w-[min(600px,calc(100vw-32px))] max-h-[calc(100vh-48px)] overflow-y-auto",
            "rounded-[var(--radius)] bg-card border border-rule shadow-card-hover",
            "p-6 md:p-8",
            "data-[state=open]:animate-in data-[state=open]:fade-in-0 data-[state=open]:zoom-in-95",
            "data-[state=open]:slide-in-from-bottom-2 duration-400 ease-out"
          )}
        >
          {/* Masthead */}
          <div className="flex items-center justify-between gap-3 mb-4">
            <div className="flex items-center gap-2.5">
              <span className="amber-rule" />
              <span className="kicker">{t("onboarding.eyebrow")}</span>
            </div>
            <span className="font-mono text-[10.5px] text-trace tracking-wider">
              {t("onboarding.stepLabel", { current: step, total: 2 })}
            </span>
          </div>

          <Dialog.Title asChild>
            <h2 className="font-display font-medium leading-[0.96] tracking-[-0.025em] mb-1">
              <span className="block text-[34px] text-ink">
                {step === 1 ? t("onboarding.step1Title") : t("onboarding.step2Title")}
              </span>
              <span className="block text-[22px] text-muted">
                <span className="serif-italic font-normal">
                  {step === 1 ? t("onboarding.step1Subtitle") : t("onboarding.step2Subtitle")}
                </span>
              </span>
            </h2>
          </Dialog.Title>

          <Dialog.Description asChild>
            <p className="text-[13.5px] text-faded mt-3 mb-6 leading-relaxed">
              {step === 1 ? t("onboarding.step1Body") : t("onboarding.step2Body")}
            </p>
          </Dialog.Description>

          {step === 1 ? (
            <Step1Form
              epType={epType}
              setEpType={setEpType}
              epName={epName}
              setEpName={(v) => { setEpName(v); setNameDirty(true); }}
              epBaseUrl={epBaseUrl}
              setEpBaseUrl={(v) => { setEpBaseUrl(v); setUrlDirty(true); setTestResult(null); }}
              epApiKey={epApiKey}
              setEpApiKey={(v) => { setEpApiKey(v); setTestResult(null); }}
              testing={testing}
              testResult={testResult}
              onTest={handleTest}
              t={t}
            />
          ) : (
            <Step2Form
              endpointLabel={epName}
              endpointType={epType}
              presets={presets}
              presetIdx={presetIdx}
              setPresetIdx={(i) => { setPresetIdx(i); setLabelDirty(false); }}
              modelMode={modelMode}
              setModelMode={(m) => { setModelMode(m); setLabelDirty(false); }}
              customModelId={customModelId}
              setCustomModelId={(v) => { setCustomModelId(v); setLabelDirty(false); }}
              modelLabel={modelLabel}
              setModelLabel={(v) => { setModelLabel(v); setLabelDirty(true); }}
              t={t}
            />
          )}

          {/* Action bar */}
          <div className="mt-7 pt-5 border-t border-rule flex items-center justify-between gap-3">
            {step === 1 ? (
              <Button variant="ghost" onClick={handleSkip}>
                {t("onboarding.skip")}
              </Button>
            ) : (
              <Button variant="ghost" onClick={handleBack}>
                <ArrowLeft size={13} />
                {t("onboarding.back")}
              </Button>
            )}
            {step === 1 ? (
              <Button
                variant="primary"
                onClick={handleNext}
                disabled={testing || !epApiKey.trim()}
              >
                {t("onboarding.next")}
                <ArrowRight size={13} />
              </Button>
            ) : (
              <Button variant="primary" onClick={handleFinish} loading={finishing}>
                {t("onboarding.finish")}
                <ArrowRight size={13} />
              </Button>
            )}
          </div>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  );
}

/* ─── Step 1: endpoint form ──────────────────────────────────────────── */

interface Step1Props {
  epType: EndpointType;
  setEpType: (v: EndpointType) => void;
  epName: string;
  setEpName: (v: string) => void;
  epBaseUrl: string;
  setEpBaseUrl: (v: string) => void;
  epApiKey: string;
  setEpApiKey: (v: string) => void;
  testing: boolean;
  testResult: ConnectionTestResult | null;
  onTest: () => void;
  t: (k: string, opts?: Record<string, unknown>) => string;
}

function Step1Form({
  epType,
  setEpType,
  epName,
  setEpName,
  epBaseUrl,
  setEpBaseUrl,
  epApiKey,
  setEpApiKey,
  testing,
  testResult,
  onTest,
  t,
}: Step1Props) {
  return (
    <div className="flex flex-col gap-4">
      <div className="grid grid-cols-1 md:grid-cols-[1.2fr_1fr] gap-3">
        <Field>
          <Label>{t("endpoint.name")}</Label>
          <Input
            value={epName}
            onChange={(e) => setEpName(e.target.value)}
            placeholder="OpenAI"
            autoFocus
          />
        </Field>
        <Field>
          <Label>{t("endpoint.type")}</Label>
          <Select value={epType} onValueChange={(v) => setEpType(v as EndpointType)}>
            <SelectItem value="openai">{t("endpoint.typeOpenai")}</SelectItem>
            <SelectItem value="google">{t("endpoint.typeGoogle")}</SelectItem>
          </Select>
        </Field>
      </div>

      <Field>
        <Label>{t("endpoint.url")}</Label>
        <Input
          value={epBaseUrl}
          onChange={(e) => setEpBaseUrl(e.target.value)}
          placeholder={DEFAULT_BASE_URL[epType]}
          mono
        />
        <Hint className="mt-1.5">{t("endpoint.urlHint")}</Hint>
      </Field>

      <Field>
        <Label>{t("endpoint.apiKey")}</Label>
        <Input
          type="password"
          value={epApiKey}
          onChange={(e) => setEpApiKey(e.target.value)}
          placeholder={epType === "openai" ? "sk-..." : "AIza..."}
          mono
        />
        <Hint className="mt-1.5">{t("endpoint.apiKeyHint")}</Hint>
      </Field>

      <div className="flex items-center gap-3 mt-1">
        <Button
          variant="outline"
          onClick={onTest}
          loading={testing}
          disabled={!epBaseUrl.trim() || !epApiKey.trim()}
        >
          <Plug size={13} />
          {testing ? t("settings.testing") : t("onboarding.test")}
        </Button>

        {testResult && (
          <div
            className={cn(
              "flex items-center gap-2 text-[12.5px] animate-in fade-in-0 slide-in-from-left-1 duration-300",
              testResult.ok ? "text-success" : "text-danger"
            )}
          >
            {testResult.ok ? (
              <CheckCircle2 size={14} strokeWidth={2} />
            ) : (
              <AlertCircle size={14} strokeWidth={2} />
            )}
            <span>
              {testResult.ok
                ? testResult.modelCount !== undefined
                  ? t("settings.testModels", { count: testResult.modelCount })
                  : t("settings.testOk")
                : testResult.message}
            </span>
          </div>
        )}
      </div>
    </div>
  );
}

/* ─── Step 2: model form ─────────────────────────────────────────────── */

interface Step2Props {
  endpointLabel: string;
  endpointType: EndpointType;
  presets: { model_id: string; label: string }[];
  presetIdx: number;
  setPresetIdx: (i: number) => void;
  modelMode: "preset" | "custom";
  setModelMode: (m: "preset" | "custom") => void;
  customModelId: string;
  setCustomModelId: (v: string) => void;
  modelLabel: string;
  setModelLabel: (v: string) => void;
  t: (k: string, opts?: Record<string, unknown>) => string;
}

function Step2Form({
  endpointLabel,
  endpointType,
  presets,
  presetIdx,
  setPresetIdx,
  modelMode,
  setModelMode,
  customModelId,
  setCustomModelId,
  modelLabel,
  setModelLabel,
  t,
}: Step2Props) {
  return (
    <div className="flex flex-col gap-4">
      {/* Endpoint chip — readonly reminder */}
      <div className="flex items-center gap-2 text-[12px] text-faded">
        <span className="eyebrow">{t("model.endpoint")}</span>
        <span className="px-2 py-0.5 rounded bg-inset border border-rule text-ink font-mono text-[11.5px]">
          {endpointLabel}
        </span>
        <span className="text-trace">·</span>
        <span>{ENDPOINT_TYPE_LABEL[endpointType]}</span>
      </div>

      <Field>
        <Label>{t("model.modelId")}</Label>
        {modelMode === "preset" ? (
          <Select
            value={String(presetIdx)}
            onValueChange={(v) => setPresetIdx(Number(v))}
          >
            {presets.map((p, i) => (
              <SelectItem key={p.model_id} value={String(i)}>
                <span className="font-medium">{p.label}</span>
                <span className="text-trace ml-2 font-mono text-[11.5px]">{p.model_id}</span>
              </SelectItem>
            ))}
          </Select>
        ) : (
          <Input
            value={customModelId}
            onChange={(e) => setCustomModelId(e.target.value)}
            placeholder={t("model.customPlaceholder")}
            mono
          />
        )}
      </Field>

      <Field>
        <Label>{t("model.customToggle")}</Label>
        <div className="h-9 flex items-center gap-3">
          <Switch
            aria-label={t("model.customToggle")}
            checked={modelMode === "custom"}
            onCheckedChange={(c) => setModelMode(c ? "custom" : "preset")}
          />
          <span className="text-[12px] text-muted">
            {modelMode === "custom" ? t("model.customOn") : t("model.customOff")}
          </span>
        </div>
        <Hint className="mt-1.5">{t("model.customHint")}</Hint>
      </Field>

      <Field>
        <Label>{t("model.label")}</Label>
        <Input
          value={modelLabel}
          onChange={(e) => setModelLabel(e.target.value)}
          placeholder={t("model.labelPlaceholder")}
        />
        <Hint className="mt-1.5">{t("model.labelHint")}</Hint>
      </Field>
    </div>
  );
}
