// src/components/TitleBar.tsx
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { platform } from "@tauri-apps/plugin-os";
import { Minus, Square, Copy, X, Sun, Moon, Monitor } from "lucide-react";
import { cn } from "@/lib/utils";
import { useConfig } from "@/services/store";

const appWindow = getCurrentWindow();

/** macOS shows native traffic-light buttons (configured via `titleBarStyle: "Overlay"`
 *  + `hiddenTitle: true` in tauri.conf.json), so we suppress our custom Min/Max/Close. */
const IS_MACOS = platform() === "macos";

function ThemeToggle() {
  const { t } = useTranslation();
  const theme = useConfig((s) => s.config.theme);
  const update = useConfig((s) => s.update);
  const next: typeof theme = theme === "light" ? "dark" : theme === "dark" ? "system" : "light";
  const Icon = theme === "light" ? Sun : theme === "dark" ? Moon : Monitor;
  return (
    <button
      type="button"
      onClick={() => update({ theme: next })}
      aria-label={t("titlebar.theme", { mode: theme })}
      className="h-8 w-[46px] inline-flex items-center justify-center text-faded hover:text-ink hover:bg-inset transition-colors"
      title={t("titlebar.theme", { mode: theme })}
    >
      <Icon size={13} strokeWidth={1.75} />
    </button>
  );
}

function WinControls() {
  const { t } = useTranslation();
  const [isMax, setMax] = useState(false);

  useEffect(() => {
    let unlisten: undefined | (() => void);
    appWindow.isMaximized().then(setMax);
    appWindow.onResized(async () => setMax(await appWindow.isMaximized()))
      .then((fn) => { unlisten = fn; });
    return () => { unlisten?.(); };
  }, []);

  return (
    <div className="flex items-stretch">
      <button
        type="button"
        onClick={() => appWindow.minimize()}
        aria-label={t("titlebar.minimize")}
        title={t("titlebar.minimize")}
        className="w-[46px] h-8 inline-flex items-center justify-center text-faded hover:text-ink hover:bg-inset transition-colors"
      >
        <Minus size={13} strokeWidth={1.5} />
      </button>
      <button
        type="button"
        onClick={() => appWindow.toggleMaximize()}
        aria-label={isMax ? t("titlebar.restore") : t("titlebar.maximize")}
        title={isMax ? t("titlebar.restore") : t("titlebar.maximize")}
        className="w-[46px] h-8 inline-flex items-center justify-center text-faded hover:text-ink hover:bg-inset transition-colors"
      >
        {isMax ? <Copy size={12} strokeWidth={1.5} /> : <Square size={11} strokeWidth={1.5} />}
      </button>
      <button
        type="button"
        onClick={() => appWindow.close()}
        aria-label={t("titlebar.close")}
        title={t("titlebar.close")}
        className={cn(
          "w-[46px] h-8 inline-flex items-center justify-center text-faded transition-colors",
          "hover:!text-[color:var(--close-hover-fg)] hover:!bg-[color:var(--close-hover)]"
        )}
      >
        <X size={14} strokeWidth={1.5} />
      </button>
    </div>
  );
}

interface Props {
  className?: string;
}

export function TitleBar({ className }: Props) {
  const { t } = useTranslation();
  return (
    <div
      className={cn(
        "h-8 shrink-0 flex items-stretch bg-paper border-b border-rule select-none",
        className
      )}
    >
      {/* Drag region — fills available space.
          On macOS, leave room for the native traffic-light buttons on the left. */}
      <div
        data-tauri-drag-region
        className={cn(
          "flex-1 min-w-0 flex items-center px-3 md:px-4 gap-2 md:gap-2.5",
          IS_MACOS && "pl-[78px]"
        )}
      >
        <span data-tauri-drag-region className="w-1.5 h-1.5 rounded-full bg-accent shrink-0" />
        <span
          data-tauri-drag-region
          className="font-mono text-[11px] tracking-[0.12em] uppercase text-faded truncate"
        >
          {t("app.title")}
        </span>
        <span data-tauri-drag-region className="hidden md:inline text-decor text-[11px]">·</span>
        <span
          data-tauri-drag-region
          className="hidden md:inline serif-italic text-[12px] text-trace truncate"
        >
          {t("app.tagline")}
        </span>
      </div>

      <ThemeToggle />

      {!IS_MACOS && (
        <>
          <div className="w-px self-stretch bg-rule my-1.5" />
          <WinControls />
        </>
      )}
    </div>
  );
}

// src/components/TitleBar.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";
import { useI18n } from "vue-i18n";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { platform } from "@tauri-apps/plugin-os";
import { useConfigStore } from "@/stores/config";

const { t } = useI18n();
const cfg = useConfigStore();
const appWindow = getCurrentWindow();

// macOS uses native traffic lights (see tauri.conf.json titleBarStyle: "Overlay")
// — hide our custom Min/Max/Close on that platform.
const IS_MACOS = platform() === "macos";

const isMax = ref(false);
let unlisten: (() => void) | undefined;

onMounted(async () => {
  isMax.value = await appWindow.isMaximized();
  unlisten = await appWindow.onResized(async () => {
    isMax.value = await appWindow.isMaximized();
  });
});

onUnmounted(() => {
  unlisten?.();
});

function cycleTheme() {
  const order: Array<"light" | "dark" | "system"> = ["light", "dark", "system"];
  const i = order.indexOf(cfg.config.theme);
  const next = order[(i + 1) % order.length];
  void cfg.update({ theme: next });
}

const themeIcon = computedTheme();
function computedTheme() {
  return computed(() => {
    if (cfg.config.theme === "light") return "i-lucide-sun";
    if (cfg.config.theme === "dark") return "i-lucide-moon";
    return "i-lucide-monitor";
  });
}

import { computed } from "vue";
</script>

<template>
  <div
    class="h-8 shrink-0 flex items-stretch bg-default border-b border-default select-none"
  >
    <!-- Drag region — fills available space. On macOS we pad-left for the traffic lights. -->
    <div
      data-tauri-drag-region
      :class="[
        'flex-1 min-w-0 flex items-center px-3 md:px-4 gap-2 md:gap-2.5',
        IS_MACOS && 'pl-[78px]',
      ]"
    >
      <span data-tauri-drag-region class="w-1.5 h-1.5 rounded-full bg-primary shrink-0" />
      <span
        data-tauri-drag-region
        class="font-mono text-[11px] tracking-[0.12em] uppercase text-muted truncate"
      >
        {{ t("app.title") }}
      </span>
      <span data-tauri-drag-region class="hidden md:inline text-toned text-[11px]">·</span>
      <span
        data-tauri-drag-region
        class="hidden md:inline italic text-[12px] text-toned truncate"
      >
        {{ t("app.tagline") }}
      </span>
    </div>

    <UButton
      variant="ghost"
      color="neutral"
      size="xs"
      :icon="themeIcon"
      :aria-label="t('titlebar.theme', { mode: cfg.config.theme })"
      :title="t('titlebar.theme', { mode: cfg.config.theme })"
      class="rounded-none w-[46px] justify-center"
      @click="cycleTheme"
    />

    <template v-if="!IS_MACOS">
      <div class="w-px self-stretch bg-default my-1.5" />
      <div class="flex items-stretch">
        <UButton
          variant="ghost"
          color="neutral"
          size="xs"
          icon="i-lucide-minus"
          :aria-label="t('titlebar.minimize')"
          :title="t('titlebar.minimize')"
          class="rounded-none w-[46px] justify-center"
          @click="appWindow.minimize()"
        />
        <UButton
          variant="ghost"
          color="neutral"
          size="xs"
          :icon="isMax ? 'i-lucide-copy' : 'i-lucide-square'"
          :aria-label="isMax ? t('titlebar.restore') : t('titlebar.maximize')"
          :title="isMax ? t('titlebar.restore') : t('titlebar.maximize')"
          class="rounded-none w-[46px] justify-center"
          @click="appWindow.toggleMaximize()"
        />
        <UButton
          variant="ghost"
          color="error"
          size="xs"
          icon="i-lucide-x"
          :aria-label="t('titlebar.close')"
          :title="t('titlebar.close')"
          class="rounded-none w-[46px] justify-center"
          @click="appWindow.close()"
        />
      </div>
    </template>
  </div>
</template>
